'use client'
import Link from 'next/link'

const EFFECTIVE_DATE = 'September 4, 2026'

const SECTIONS = [
  {
    title: '1. Agreement to Terms',
    body: `By creating an account, accessing, or using Daybase (the "Service"), you agree to these Terms of Service ("Terms"). If you don't agree, please don't use the Service. Daybase is intended for business use by adults who can form a legally binding contract — you must be at least 18 years old to use it.`,
  },
  {
    title: '2. What Daybase Is',
    body: `Daybase provides a set of AI-powered tools that help service-based businesses generate written content for running their day-to-day work: client proposals and quotes, appointment and job update messages, call scripts and missed-call responses, review requests, social media posts, service agreements, client onboarding packets, translations, and bid/RFP analysis. Daybase writes drafts based on the information you provide — it is a writing tool, not a substitute for your own judgment, legal advice, or professional review.`,
  },
  {
    title: '3. Your Account & Data You Provide',
    body: `Daybase does not require a traditional account or password. Your company profile, proposal history, and related content are stored locally in your own web browser and are not stored on Daybase's servers. This means clearing your browser data, switching browsers, or switching devices will remove this information, and Daybase cannot recover it for you. You're responsible for keeping your own backups — for example, by downloading generated PDFs — of anything you want to keep.`,
  },
  {
    title: '4. AI-Generated Content',
    body: `Content generated by Daybase is produced by an AI model based on what you type in. While it's designed to write clear, professional drafts, AI can make mistakes — it may occasionally get a fact, number, or detail wrong, especially if it wasn't given accurate information to begin with. You're responsible for reviewing, fact-checking, and editing any generated content before sending it to a client or relying on it for a business decision. Daybase is not liable for losses arising from inaccuracies in AI-generated content that you did not review before use.`,
  },
  {
    title: '5. Plans & Payment',
    body: `Daybase offers a free tier (2 proposal generations per rolling 30-day period, no payment method required) and paid options for proposal generation: a one-time per-proposal purchase, or an Unlimited monthly subscription. Every other tool — customer updates, the call assistant, review requests, social posts, service agreements, onboarding packets, translation, and bid analysis — is free to use with any account, on any plan.

All payments are processed securely by Stripe, Inc. Daybase never receives or stores your full card number or payment credentials.

One-time proposal purchases are charged immediately and are generally non-refundable once the corresponding proposal has been generated, since the service is delivered instantly and in full.

The Unlimited subscription renews automatically each month until canceled. You may cancel at any time; your access continues through the end of the billing period you've already paid for, and you won't be charged again after that. We don't provide prorated refunds for partial billing periods.`,
  },
  {
    title: '6. Acceptable Use',
    body: `You agree not to use Daybase to generate content that is illegal, fraudulent, or intended to deceive; to violate another person's or business's rights; to reverse-engineer, scrape, or resell the Service without permission; or to overload or attack Daybase's systems. We may suspend or terminate access for violations of this section.`,
  },
  {
    title: '7. Ownership',
    body: `You own the content you generate through Daybase for use in your own business — your proposals, messages, and documents are yours to send and use. Daybase and its owner retain all rights to the underlying software, design, branding, and technology that power the Service.`,
  },
  {
    title: '8. Service Availability',
    body: `Daybase is provided on an "as-is" and "as-available" basis. We do our best to keep the Service running reliably, but we don't guarantee uninterrupted or error-free operation, and we may modify, suspend, or discontinue features at any time.`,
  },
  {
    title: '9. Disclaimer of Warranties & Limitation of Liability',
    body: `To the fullest extent permitted by law, Daybase is provided without warranties of any kind, express or implied. Daybase and its owner won't be liable for indirect, incidental, or consequential damages arising from your use of the Service, including lost business, lost revenue, or reliance on AI-generated content. Our total liability for any claim relating to the Service is limited to the amount you paid Daybase in the 3 months before the claim arose.`,
  },
  {
    title: '10. Changes to These Terms',
    body: `We may update these Terms from time to time as Daybase grows. If we make material changes, we'll update the effective date above. Continuing to use Daybase after changes take effect means you accept the updated Terms.`,
  },
  {
    title: '11. Governing Law',
    body: `These Terms are governed by the laws of the Commonwealth of Massachusetts, USA, without regard to conflict-of-law principles.`,
  },
  {
    title: '12. Contact',
    body: `Questions about these Terms? Reach us at support@daybase.io.`,
  },
]

export default function Terms() {
  return (
    <div className="min-h-screen flex flex-col" style={{ backgroundColor: 'var(--cream)' }}>
      <header className="nav-glass-light" style={{ borderBottom: '1px solid var(--hairline)' }}>
        <div className="max-w-3xl mx-auto px-8 py-6 flex items-center justify-between">
          <Link
            href="/"
            className="text-2xl tracking-wide"
            style={{ fontFamily: 'var(--font-serif)', color: 'var(--navy)' }}
          >
            Daybase
          </Link>
          <nav className="flex gap-6 text-xs tracking-[0.2em] uppercase">
            <Link href="/privacy" className="link-gold" style={{ color: 'var(--charcoal)' }}>Privacy</Link>
            <Link href="/pricing" className="link-gold" style={{ color: 'var(--charcoal)' }}>Pricing</Link>
          </nav>
        </div>
      </header>

      <main className="flex-1 max-w-3xl w-full mx-auto px-8 py-16 fade-in-up">
        <div className="text-xs tracking-[0.3em] uppercase mb-4" style={{ color: 'var(--gold)' }}>
          Legal
        </div>
        <h1 className="text-4xl mb-3" style={{ fontFamily: 'var(--font-serif)', color: 'var(--navy)' }}>
          Terms of Service
        </h1>
        <p className="text-sm mb-14" style={{ color: 'rgba(34,38,47,0.5)' }}>
          Effective {EFFECTIVE_DATE}
        </p>

        <div className="flex flex-col gap-10">
          {SECTIONS.map((s) => (
            <div key={s.title}>
              <h2 className="text-lg mb-3" style={{ fontFamily: 'var(--font-serif)', color: 'var(--navy)' }}>
                {s.title}
              </h2>
              <p
                className="text-sm leading-relaxed whitespace-pre-line"
                style={{ color: 'rgba(34,38,47,0.68)' }}
              >
                {s.body}
              </p>
            </div>
          ))}
        </div>
      </main>

      <footer
        className="px-8 py-6 text-center text-xs"
        style={{ borderTop: '1px solid var(--hairline)', color: 'rgba(34,38,47,0.4)' }}
      >
        <Link href="/privacy" className="link-gold uppercase tracking-[0.15em]">Privacy Policy</Link>
        <span className="mx-3">·</span>
        Daybase — Run your business, without the busywork
      </footer>
    </div>
  )
}
